Repository Badger-Finance/badger-sdk, pull requests merged in 2022-04, with the labels that each got.

#115 fix: add error logging for request failures + remove load schedule qu…
  src/api/index.ts
Labels: bug

#133 chore: update network support + tests
  src/api/index.ts
  src/config/constants.ts
  src/config/enums/network.enum.ts
  src/config/index.ts
  src/config/interfaces/index.ts
  src/config/interfaces/network-config.interface.ts
  src/config/maps/index.ts
  src/config/maps/network.id.map.ts
  src/config/network/arbitrum.config.ts
  src/config/network/avalanche.config.ts
  src/config/network/binance.config.ts
  src/config/network/ethereum.config.ts
  src/config/network/fantom.config.ts
  src/config/network/index.ts
  src/config/network/local.config.ts
  src/config/network/network.config.spec.ts
  src/config/network/network.config.ts
  src/config/network/polygon.config.ts
  src/digg/digg.service.ts
  src/ibbtc/ibbtc.service.ts
  src/rewards/rewards.service.ts
  src/sdk.ts
  src/service.ts
  src/utils/checksum-entries.ts
  src/utils/index.ts
Labels: enhancement

#134 test: add initial vault service mocking
  package.json
  src/utils/checksum-entries.ts
  src/utils/index.ts
  src/utils/key-by.spec.ts
  src/vaults/__snapshots__/vaults.service.spec.ts.snap
  src/vaults/vaults.service.spec.ts
  src/vaults/vaults.service.ts
  yarn.lock
Labels: test

#135 fix: vaults list harvest and deployed at script
  .eslintignore
  mocks.pkg/.env.example
  mocks.pkg/src/types.ts
  package.json
  scripts/vaults/deployed.at.ts
  src/common/interfaces/blocks-range-options.interface.ts
  src/common/interfaces/range-options.interface.ts
  src/utils/chunk-query-filter.ts
  src/vaults/data/deployed.at.json
  src/vaults/interfaces/list-harvest-options.interface.ts
  src/vaults/interfaces/vault-deployed-at.interface.ts
  src/vaults/vaults.service.spec.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
Labels: enhancement

#136 feat: enable api mocks
  mocks.pkg/.env.example
  mocks.pkg/__cache__/methods.json
  mocks.pkg/generated/ethereum/api/loadAccount.json
  mocks.pkg/generated/ethereum/api/loadCharts.json
  mocks.pkg/generated/ethereum/api/loadGasPrices.json
  mocks.pkg/generated/ethereum/api/loadLeaderboardSummary.json
  mocks.pkg/generated/ethereum/api/loadPrices.json
  mocks.pkg/generated/ethereum/api/loadProof.json
  mocks.pkg/generated/ethereum/api/loadProtocolMetrics.json
  mocks.pkg/generated/ethereum/api/loadProtocolSummary.json
  mocks.pkg/generated/ethereum/api/loadRewardTree.json
  mocks.pkg/generated/ethereum/api/loadSchedule.json
  mocks.pkg/generated/ethereum/api/loadSchedules.json
  mocks.pkg/generated/ethereum/api/loadSetts.json
  mocks.pkg/generated/ethereum/api/loadTokens.json
  mocks.pkg/generated/ethereum/api/loadVault.json
  mocks.pkg/generated/ethereum/api/loadVaults.json
  mocks.pkg/generated/ethereum/rewards/loadSchedules.json
  mocks.pkg/generated/ethereum/vaults/getVaultStrategy.json
  mocks.pkg/generated/polygon/api/loadAccount.json
  mocks.pkg/generated/polygon/api/loadCharts.json
  mocks.pkg/generated/polygon/api/loadGasPrices.json
  mocks.pkg/generated/polygon/api/loadLeaderboardSummary.json
  mocks.pkg/generated/polygon/api/loadPrices.json
  mocks.pkg/generated/polygon/api/loadProof.json
  mocks.pkg/generated/polygon/api/loadProtocolMetrics.json
  mocks.pkg/generated/polygon/api/loadProtocolSummary.json
  mocks.pkg/generated/polygon/api/loadRewardTree.json
  mocks.pkg/generated/polygon/api/loadSchedule.json
  mocks.pkg/generated/polygon/api/loadSchedules.json
  mocks.pkg/generated/polygon/api/loadSetts.json
  mocks.pkg/generated/polygon/api/loadTokens.json
  mocks.pkg/generated/polygon/api/loadVault.json
  mocks.pkg/generated/polygon/api/loadVaults.json
  mocks.pkg/generated/polygon/rewards/loadSchedules.json
  mocks.pkg/src/cache/methods.cache.ts
  mocks.pkg/src/cache/struct.types.cache.ts
  mocks.pkg/src/config/base.config.ts
  mocks.pkg/src/enums/sdk.services.enum.ts
  mocks.pkg/src/processor/mocks.processor.ts
Labels: enhancement

#144 fix: digg addr matching
  src/digg/digg.service.ts
  src/rewards/rewards.service.ts
Labels: bug

#145 feat: add funding rate support
  src/api/interfaces/citadel-treasury-summary.interface.ts
  src/api/interfaces/index.ts
  src/citadel/citadel.service.ts
  src/citadel/interfaces/citadel-mint-distribution.interface.ts
Labels: enhancement

#146 chore: add new citadel support + update contracts
  examples/citadel.ts
  examples/harvests.ts
  mocks.pkg/__cache__/methods.json
  mocks.pkg/generated/ethereum/api/loadAccount.json
  mocks.pkg/generated/ethereum/api/loadCharts.json
  mocks.pkg/generated/ethereum/api/loadCitadelTreasury.json
  mocks.pkg/generated/ethereum/api/loadCitadelTreasuryCharts.json
  mocks.pkg/generated/ethereum/api/loadCitadelUserTotalRewards.json
  mocks.pkg/generated/ethereum/api/loadGasPrices.json
  mocks.pkg/generated/ethereum/api/loadLeaderboardSummary.json
  mocks.pkg/generated/ethereum/api/loadPrices.json
  mocks.pkg/generated/ethereum/api/loadProtocolMetrics.json
  mocks.pkg/generated/ethereum/api/loadProtocolSummary.json
  mocks.pkg/generated/ethereum/api/loadRewardTree.json
  mocks.pkg/generated/ethereum/api/loadSchedules.json
  mocks.pkg/generated/ethereum/api/loadSett.json
  mocks.pkg/generated/ethereum/api/loadSetts.json
  mocks.pkg/generated/ethereum/api/loadTokens.json
  mocks.pkg/generated/ethereum/api/loadVault.json
  mocks.pkg/generated/ethereum/api/loadVaults.json
  mocks.pkg/generated/ethereum/graph/loadBadgerTreeDistributions.json
  mocks.pkg/generated/ethereum/graph/loadSett.json
  mocks.pkg/generated/ethereum/graph/loadSettHarvests.json
  mocks.pkg/generated/ethereum/graph/loadSetts.json
  mocks.pkg/generated/ethereum/graph/loadStrategies.json
  mocks.pkg/generated/ethereum/rewards/loadSchedules.json
  mocks.pkg/generated/ethereum/vaults/loadVault.json
  mocks.pkg/generated/ethereum/vaults/loadVaults.json
  mocks.pkg/generated/polygon/api/loadCitadelTreasuryCharts.json
  mocks.pkg/generated/polygon/api/loadCitadelUserTotalRewards.json
  mocks.pkg/generated/polygon/api/loadGasPrices.json
  mocks.pkg/generated/polygon/api/loadLeaderboardSummary.json
  mocks.pkg/generated/polygon/api/loadPrices.json
  mocks.pkg/generated/polygon/api/loadProtocolMetrics.json
  mocks.pkg/generated/polygon/api/loadProtocolSummary.json
  mocks.pkg/generated/polygon/api/loadSett.json
  mocks.pkg/generated/polygon/api/loadSetts.json
  mocks.pkg/generated/polygon/api/loadTokens.json
  mocks.pkg/generated/polygon/api/loadVaults.json
  mocks.pkg/generated/polygon/graph/loadSettSpanshots.json
  mocks.pkg/generated/polygon/graph/loadSetts.json
  mocks.pkg/generated/polygon/graph/loadStrategies.json
  mocks.pkg/generated/polygon/graph/loadTransfers.json
  mocks.pkg/generated/polygon/graph/loadUserSettBalances.json
  mocks.pkg/generated/polygon/graph/loadUsers.json
  mocks.pkg/generated/polygon/vaults/loadVaults.json
  mocks.pkg/src/config/base.config.ts
  mocks.pkg/src/config/polygon.config.ts
  src/api/enums/chart-granularity.enum.ts
  src/api/enums/chart-timeframe.enum.ts
  src/api/enums/index.ts
  src/api/index.ts
  src/api/interfaces/citadel-reward-event.interface.ts
  src/api/interfaces/index.ts
  src/api/interfaces/treasury-summary-snapshot.interface.ts
  src/api/interfaces/treasury-summary.interface.ts
  src/citadel/citadel.service.ts
  src/citadel/interfaces/index.ts
  src/digg/digg.service.ts
  src/rewards/rewards.service.ts
Labels: enhancement

#148 fix: update sdk mocks
  mocks.pkg/generated/ethereum/api/loadCitadelTreasury.json
  src/api/interfaces/citadel-treasury-summary.interface.ts
Labels: bug

#151 chore: add potential protocols + btc currency
  src/api/enums/currency.enum.ts
  src/api/enums/protocol.enum.ts
Labels: enhancement

#153 fix: update export
  src/api/interfaces/index.ts
Labels: bug, enhancement

#155 fix: extend citadel treasury summary
  src/api/interfaces/citadel-treasury-summary.interface.ts
Labels: enhancement
