Repository Badger-Finance/badger-sdk, pull requests merged in 2022-08, with the labels that each got.

#238 fix: citadel removal + mocks cleanup + provider mocking hooks
  mocks.pkg/__cache__/methods.json
  mocks.pkg/generated/ethereum/api/loadCitadelAccount.json
  mocks.pkg/generated/ethereum/api/loadCitadelKnightingRoundLeaderboard.json
  mocks.pkg/generated/ethereum/api/loadCitadelMerkleProof.json
  mocks.pkg/generated/ethereum/api/loadCitadelSummary.json
  mocks.pkg/generated/ethereum/api/loadCitadelTreasury.json
  mocks.pkg/generated/ethereum/api/loadCitadelTreasuryCharts.json
  mocks.pkg/generated/ethereum/api/loadCitadelUserTotalRewards.json
  mocks.pkg/src/config/base.config.ts
  mocks.pkg/src/constants.ts
  mocks.pkg/src/processor/mocks.processor.ts
  src/api/index.ts
  src/api/interfaces/api-options.interface.ts
  src/api/interfaces/citadel-account.interface.ts
  src/api/interfaces/citadel-leaderboard-entry.interface.ts
  src/api/interfaces/citadel-reward-event.interface.ts
  src/api/interfaces/citadel-summary.interface.ts
  src/api/interfaces/citadel-treasury-summary.interface.ts
  src/api/interfaces/index.ts
  src/api/interfaces/treasury-summary-snapshot.interface.ts
  src/api/interfaces/treasury-summary.interface.ts
  src/api/interfaces/treasy-position.interface.ts
  src/api/interfaces/vault-yield-projection.interface.ts
  src/citadel/__snapshots__/citadel.service.spec.ts.snap
  src/citadel/__snapshots__/citadel.utils.spec.ts.snap
  src/citadel/citadel.service.spec.ts
  src/citadel/citadel.service.ts
  src/citadel/citadel.utils.spec.ts
  src/citadel/citadel.utils.ts
  src/citadel/enums/index.ts
  src/citadel/enums/reward-data-type.enum.ts
  src/citadel/enums/reward-event-type.enum.ts
  src/citadel/enums/reward-filter.enum.ts
  src/citadel/errors/citadel.error.constants.ts
  src/citadel/errors/citadel.init.error.ts
  src/citadel/errors/citadel.validation.error.ts
  src/citadel/errors/index.ts
  src/citadel/index.ts
  src/citadel/interfaces/citadel-mint-distribution.interface.ts
  src/citadel/interfaces/index.ts
  src/citadel/interfaces/list-distribution-options.interface.ts
  src/citadel/interfaces/list-rewards-event.interface.ts
  src/citadel/interfaces/list-rewards-options.interface.ts
  src/citadel/interfaces/merkle-distribution.interface.ts
  src/citadel/interfaces/merkle-proof.interface.ts
  src/citadel/interfaces/minter-distribution-data.interface.ts
  src/citadel/interfaces/minter-distribution-event.interface.ts
  src/citadel/mocks/added-reward-events.mock.ts
  src/citadel/mocks/distribution-formatted-events.mock.ts
  src/citadel/mocks/distribution-to-staking-events.mock.ts
  src/citadel/mocks/paid-reward-events.mock.ts
  src/index.spec.ts
  src/index.ts
  src/sdk.ts
  src/tests/index.ts
  src/tests/tests.utils.ts
Labels: bug

#241 fix: remove tests package
  src/index.ts
Labels: bug

#240 fix: update vault dto mocks
  mocks.pkg/__cache__/methods.json
  mocks.pkg/generated/ethereum/api/loadVault.json
  mocks.pkg/generated/ethereum/api/loadVaultChart.json
  mocks.pkg/generated/ethereum/api/loadVaults.json
  mocks.pkg/src/config/base.config.ts
  mocks.pkg/src/processor/mocks.processor.ts
  src/api/index.ts
Labels: enhancement

#242 fix: update vault dto view
  src/api/interfaces/vault-dto.interface.ts
Labels: enhancement

#244 fix: test compatibilities
  package.json
  src/config/constants.ts
  src/digg/digg.service.ts
  src/ibbtc/ibbtc.service.ts
  src/registry/registry.service.ts
  src/rewards/rewards.service.ts
  src/vaults/vaults.service.ts
  yarn.lock
Labels: enhancement, test

#245 fix: align ethers + 0xsequence dependencies
  package.json
  yarn.lock
Labels: enhancement

#247 fix: check for registry before attempting to load vaults
  src/registry/registry.service.ts
  src/rewards/rewards.service.ts
Labels: bug

#248 fix: add emission control
  mocks.pkg/__cache__/methods.json
  mocks.pkg/generated/ethereum/registry/get.json
  mocks.pkg/generated/ethereum/registry/getFilteredProductionVaults.json
  mocks.pkg/generated/ethereum/registry/getProductionVaults.json
  mocks.pkg/generated/ethereum/registry/getVaults.json
  mocks.pkg/generated/ethereum/registry/keysCount.json
  mocks.pkg/generated/ethereum/rewards/getBoostWeight.json
  mocks.pkg/generated/ethereum/rewards/hasEmissionControl.json
  mocks.pkg/generated/ethereum/vaults/listHarvests.json
  mocks.pkg/generated/ethereum/vaults/loadVault.json
  mocks.pkg/generated/ethereum/vaults/loadVaults.json
  mocks.pkg/src/config/base.config.ts
  mocks.pkg/src/constants.ts
  src/abi/emisison-control.abi
  src/registry/enums/registry-key.enum.ts
  src/rewards/rewards.service.ts
Labels: enhancement

#249 fix: update vault method inputs
  mocks.pkg/__cache__/methods.json
  mocks.pkg/generated/ethereum/vaults/getDepositCaps.json
  mocks.pkg/generated/ethereum/vaults/getPendingHarvest.json
  mocks.pkg/generated/ethereum/vaults/getPendingYield.json
  mocks.pkg/generated/ethereum/vaults/getVaultStrategy.json
  mocks.pkg/generated/ethereum/vaults/listHarvests.json
  mocks.pkg/generated/ethereum/vaults/loadVault.json
  mocks.pkg/generated/ethereum/vaults/loadVaults.json
  mocks.pkg/src/config/base.config.ts
  mocks.pkg/src/constants.ts
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
Labels: enhancement

#250 tests: mocks package, setup + coverage
  .github/workflows/test.yml
  jest.config.js
  mocks.pkg/.eslintrc
  mocks.pkg/.prettierrc.js
  mocks.pkg/jest.config.js
  mocks.pkg/jest.config.ts
  mocks.pkg/package.json
  mocks.pkg/src/cache/__snapshots__/methods.cache.spec.ts.snap
  mocks.pkg/src/cache/methods.cache.spec.ts
  mocks.pkg/src/cache/methods.cache.ts
  mocks.pkg/src/cache/mocks/__cache__.methods.mocks.ts
  mocks.pkg/src/cache/mocks/methods.cache.test.cls.mock.ts
  mocks.pkg/src/cache/mocks/methods.chache.test.wrapper.ts
  mocks.pkg/src/cache/struct.types.cache.ts
  mocks.pkg/src/config/base.config.ts
  mocks.pkg/src/config/services.config.ts
  mocks.pkg/src/fs.io/base.fs.io.spec.ts
  mocks.pkg/src/fs.io/base.fs.io.ts
  mocks.pkg/src/fs.io/index.ts
  mocks.pkg/src/index.ts
  mocks.pkg/src/processor/mocks.processor.ts
  mocks.pkg/tsconfig.json
  mocks.pkg/yarn.lock
Labels: test

#251 chore: import plugin and rules upds for sdk/mocks.pkg
  .eslintrc.js
  mocks.pkg/.eslintrc.js
  mocks.pkg/package.json
  mocks.pkg/src/cache/methods.cache.spec.ts
  mocks.pkg/src/cache/methods.cache.ts
  mocks.pkg/src/cache/struct.types.cache.ts
  mocks.pkg/src/config/base.config.ts
  mocks.pkg/src/config/polygon.config.ts
  mocks.pkg/src/config/services.config.spec.ts
  mocks.pkg/src/config/services.config.ts
  mocks.pkg/src/constants.ts
  mocks.pkg/src/fs.io/base.fs.io.spec.ts
  mocks.pkg/src/fs.io/base.fs.io.ts
  mocks.pkg/src/launch.ts
  mocks.pkg/src/processor/mocks.processor.ts
  package.json
  yarn.lock
Labels: enhancement

#252 fix: utilize read only provider
  src/vaults/vaults.service.ts
Labels: bug

#253 test: cover mocks processor main entry
  mocks.pkg/jest.config.ts
  mocks.pkg/package.json
  mocks.pkg/src/processor/mocks.processor.spec.ts
  mocks.pkg/src/processor/mocks.processor.ts
  mocks.pkg/src/processor/mocks/eth.methods.config.mock.ts
  mocks.pkg/src/processor/mocks/mocks.processor.test.wrapper.ts
  mocks.pkg/src/processor/mocks/package.mock.json
Labels: test
