Repository Badger-Finance/badger-sdk, pull requests merged in 2022-03, with the labels that each got.

#59 fix: add apy support fields
  src/api/interfaces/vault.interface.ts
Labels: enhancement

#58 chore: enforce husky install
  package.json
Labels: enhancement

#60 fix(): Use path parameter for address in `/proofs`
  src/api/index.ts
  src/index.spec.ts
  src/sdk.ts
Labels: bug

#61 fix(): Remove unused `chain` parameter from `/metrics`
  src/api/index.ts
Labels: bug

#66 fix: update vault dca to behavior field
  src/api/interfaces/vault.interface.ts
  src/vaults/enums/index.ts
  src/vaults/enums/vault-behavior.enum.ts
Labels: enhancement

#69 chore: add available to sett fragment
  src/graphql/fragments/sett.fragment.graphql
  src/graphql/generated/badger.ts
Labels: enhancement

#68 chore: add user query
  src/graphql/index.ts
Labels: enhancement

#70 fix: update charts endpoint params + update value source vars
  src/api/index.ts
  src/api/interfaces/index.ts
  src/api/interfaces/load-charts-optoins.interface.ts
  src/api/interfaces/value-source.interface.ts
Labels: enhancement

#71 fix: export vault interface + remove duplicate postfix
  src/graphql/index.ts
  src/test.ts
  src/vaults/interfaces/index.ts
  src/vaults/vaults.service.ts
Labels: bug

#73 chore: add graphql balance
  src/graphql/generated/badger.ts
Labels: bug

#77 chore: add initial parse event tests + update snapshot interface
  README.md
  package.json
  src/api/interfaces/vault-snapshot.interface.ts
  src/config/network/network.config.ts
  src/graphql/index.ts
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/interfaces/index.ts
  src/vaults/interfaces/vault-harvest-data.interface.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
Labels: enhancement

#78 chore: update vault snapshot interface
  src/api/interfaces/vault-snapshot.interface.ts
Labels: bug

#86 enhancement: add vaults v1.5 projected yield support
  src/api/interfaces/index.ts
  src/api/interfaces/token-value.interface.ts
  src/api/interfaces/vault-data.interface.ts
  src/api/interfaces/vault.interface.ts
  src/tokens/interfaces/index.ts
  src/tokens/interfaces/token-balance.interface.ts
  src/vaults/vaults.service.ts
Labels: enhancement

#84 chore: update test workflow, add local development doc, update README
  .github/workflows/test.yml
  README.md
  docs/local-testing.md
  yarn.lock
Labels: documentation

#85 chore: add vaults v1.5 event handling
  src/api/interfaces/index.ts
  src/api/interfaces/token-value.interface.ts
  src/api/interfaces/vault-data.interface.ts
  src/api/interfaces/vault.interface.ts
  src/tokens/interfaces/index.ts
  src/tokens/interfaces/token-balance.interface.ts
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/interfaces/index.ts
  src/vaults/interfaces/vault-harvest-data.interface.ts
  src/vaults/interfaces/vault-harvest-event.interface.ts
  src/vaults/interfaces/vault-performance-event.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.ts
Labels: enhancement

#88 test: vaults utilts full coverage
  .gitignore
  jest.config.js
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
Labels: test

#89 fix: add support for pending harvests
  src/vaults/vaults.service.ts
Labels: enhancement

#90 feat: badger contracts support
  src/api/index.ts
  src/api/interfaces/index.ts
  src/api/interfaces/vault-dto.interface.ts
  src/api/interfaces/vault-yield-projection.interface.ts
  src/index.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
Labels: enhancement

#91 fix: update vault projection interface
  src/api/interfaces/account.interface.ts
  src/api/interfaces/api-options.interface.ts
  src/api/interfaces/graph-options.interface.ts
  src/api/interfaces/index.ts
  src/api/interfaces/leaderboard-data.interface.ts
  src/api/interfaces/vault-yield-projection.interface.ts
Labels: enhancement

#93 fix: update snapshot for strategy tracking
  src/api/interfaces/vault-dto.interface.ts
  src/api/interfaces/vault-snapshot.interface.ts
Labels: enhancement

#95 fix: remove lint on build
  package.json
Labels: bug

#98 fix: token service fragile method update
  src/api/interfaces/index.ts
  src/registry/registry.service.ts
  src/tokens/tokens.service.ts
Labels: enhancement

#99 fix: allow unregistered vault queries
  src/registry/registry.service.ts
  src/sdk.ts
  src/vaults/vaults.service.ts
Labels: enhancement

#100 fix: remove vault version check
  src/vaults/vaults.service.ts
Labels: bug

#101 fix: add rewards initial prep + harvest caller
  src/sdk.ts
  src/vaults/vaults.service.ts
Labels: bug

#103 refactor: require vault versions in service methods
  src/registry/registry.service.ts
  src/sdk.ts
  src/vaults/interfaces/get-vault-strategy-options.interface.ts
  src/vaults/interfaces/index.ts
  src/vaults/interfaces/list-harvest-options.interface.ts
  src/vaults/interfaces/list-vault-options.interface.ts
  src/vaults/vaults.service.ts
Labels: enhancement

#105 fix: support schedules api
  src/api/index.ts
  src/api/interfaces/index.ts
  src/api/interfaces/reward-schedules-summary.interface.ts
Labels: enhancement

#107 Chore: Get vault strategy should return strat address
  src/vaults/vaults.service.spec.ts
  src/vaults/vaults.service.ts
Labels: enhancement

#108 fix: add missing aum fee to strategy
  src/api/interfaces/vault-strategy.interface.ts
Labels: enhancement
