Repository Badger-Finance/badger-sdk, pull requests merged in 2022-06, with the labels that each got.

#181 fix: update citadel locker addr
  src/citadel/citadel.service.ts
Labels: bug

#179 feat: registryV2 service integration
  mocks.pkg/package.json
  mocks.pkg/src/config/base.config.ts
  mocks.pkg/src/config/services.config.ts
  package.json
  src/abi/registry-v2.abi
  src/registry.v2/__snapshots__/registry.v2.service.spec.ts.snap
  src/registry.v2/index.ts
  src/registry.v2/interfaces/index.ts
  src/registry.v2/interfaces/vault-registry-v2-entry.interface.ts
  src/registry.v2/interfaces/vault-registry-v2-metadata.interface.ts
  src/registry.v2/mocks/registry-v2-all-production-vaults.mock.ts
  src/registry.v2/mocks/registry-v2-production-vaults.mock.ts
  src/registry.v2/registry.v2.service.spec.ts
  src/registry.v2/registry.v2.service.ts
  src/registry.v2/registry.v2.utils.ts
  src/rewards/rewards.service.ts
  src/sdk.ts
  src/tests/tests.constants.ts
  src/vaults/enums/index.ts
  src/vaults/enums/vault-status.enum.ts
  src/vaults/interfaces/load-vault-options.interface.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.ts
  src/vaults/vautls.constants.ts
Labels: enhancement

#182 fix: update mocks gen
  mocks.pkg/package.json
  mocks.pkg/src/config/services.config.ts
Labels: bug

#183 fix: update entry field name
  src/api/interfaces/citadel-leaderboard-entry.interface.ts
  src/vaults/vaults.utils.ts
Labels: bug

#184 fix: citadel support override
  src/citadel/citadel.service.ts
Labels: enhancement

#187 fix: update account interface extension fields
  src/api/interfaces/account.interface.ts
  src/api/interfaces/user-boost-data.interface.ts
Labels: enhancement

#189 chore: add initial testing harness functions
  src/tests/interfaces/mock-vault-system.interface.ts
  src/tests/tests.utils.ts
  src/vaults/vaults.service.spec.ts
Labels: test

#192 chore: add full increase allowance coverage
  jest.config.js
  src/tests/tests.constants.ts
  src/tests/tests.utils.ts
  src/tokens/__snapshots__/tokens.service.spec.ts.snap
  src/tokens/interfaces/index.ts
  src/tokens/interfaces/revoke-allowance-options.interface.ts
  src/tokens/tokens.service.spec.ts
  src/tokens/tokens.service.ts
Labels: test

#194 fix: add client field to regV2 metadata
  mocks.pkg/src/constants.ts
  src/registry.v2/enums/metadata.client.enum.ts
  src/registry.v2/interfaces/vault-registry-v2-metadata.interface.ts
Labels: enhancement

#197 chore: update eslintrc + sort imports
  .eslintrc.js
  package.json
  src/api/index.ts
  src/api/interfaces/api-options.interface.ts
  src/api/interfaces/index.ts
  src/api/interfaces/protocol-summary.interface.ts
  src/api/interfaces/vault-dto.interface.ts
  src/api/types/index.ts
  src/citadel/citadel.service.spec.ts
  src/citadel/citadel.service.ts
  src/citadel/citadel.utils.spec.ts
  src/citadel/citadel.utils.ts
  src/citadel/errors/index.ts
  src/citadel/index.ts
  src/citadel/interfaces/index.ts
  src/citadel/interfaces/list-rewards-event.interface.ts
  src/citadel/mocks/distribution-formatted-events.mock.ts
  src/common/interfaces/index.ts
  src/config/index.ts
  src/config/network/network.config.spec.ts
  src/digg/digg.service.ts
  src/graphql/index.ts
  src/index.ts
  src/registry.v2/interfaces/vault-registry-v2-entry.interface.ts
  src/registry.v2/registry.v2.service.spec.ts
  src/registry.v2/registry.v2.service.ts
  src/registry.v2/registry.v2.utils.ts
  src/registry/interfaces/registry-vault.interface.ts
  src/registry/registry.service.ts
  src/rewards/rewards.service.ts
  src/sdk.ts
  src/service.ts
  src/tests/interfaces/mock-vault-system.interface.ts
  src/tests/tests.utils.ts
  src/tokens/index.ts
  src/tokens/interfaces/increase-allowance-options.interface.ts
  src/tokens/interfaces/index.ts
  src/tokens/interfaces/token-action-options.interface.ts
  src/tokens/tokens.service.spec.ts
  src/tokens/tokens.service.ts
  src/utils/chunk-query-filter.spec.ts
  src/vaults/index.ts
  src/vaults/interfaces/index.ts
  src/vaults/interfaces/list-harvest-options.interface.ts
  src/vaults/interfaces/load-vault-options.interface.ts
  src/vaults/interfaces/vault-action-options.interface.ts
  src/vaults/vaults.service.spec.ts
  src/vaults/vaults.service.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
  yarn.lock
Labels: enhancement

#201 chore: utilize signer
  src/rewards/rewards.service.ts
Labels: bug

#195 chore: update example
  examples/registry.ts
Labels: documentation

#202 fix: upgrade claim for ui usage
  src/config/interfaces/index.ts
  src/config/interfaces/transaction-callback-input.interface.ts
  src/config/interfaces/transaction-options.interface.ts
  src/rewards/interfaces/claim-options.interface.ts
  src/rewards/rewards.service.ts
  src/tokens/interfaces/token-action-callback-input.interface.ts
  src/tokens/interfaces/token-action-options.interface.ts
Labels: enhancement

#204 fix: deposit + withdraw txs
  src/vaults/vaults.service.ts
Labels: enhancement

#206 fix: allow optional overrides
  package.json
  src/ibbtc/ibbtc.service.ts
  yarn.lock
Labels: bug

#208 feat: add ibbtc mint / redeem enhanced functionality
  mocks.pkg/__cache__/methods.json
  mocks.pkg/generated/ethereum/ibbtc/estimateMint.json
  mocks.pkg/generated/ethereum/ibbtc/estimateRedeem.json
  mocks.pkg/src/config/base.config.ts
  mocks.pkg/src/constants.ts
  src/abi/token-zap.abi
  src/abi/vault-peak.abi
  src/abi/vault-zap.abi
  src/ibbtc/enums/ibbtc-zap-type.enum.ts
  src/ibbtc/enums/index.ts
  src/ibbtc/ibbtc.config.ts
  src/ibbtc/ibbtc.service.ts
  src/ibbtc/index.ts
  src/ibbtc/interfaces/ibbtc-action-options.interface.ts
  src/utils/checksum.ts
  src/vaults/vaults.service.ts
Labels: enhancement

#209 fix: utlize proper rpc for token changes
  src/tokens/tokens.service.ts
  src/vaults/vaults.service.ts
Labels: bug

#210 chore: add vault harvest query support
  mocks.pkg/__cache__/methods.json
  mocks.pkg/generated/ethereum/api/loadVaultHarvests.json
  mocks.pkg/generated/ethereum/api/loadVaultsHarvests.json
  mocks.pkg/src/config/base.config.ts
  src/api/enums/harvest-type.enum.ts
  src/api/enums/index.ts
  src/api/index.ts
  src/api/interfaces/index.ts
  src/api/interfaces/vault-earning.interface.ts
Labels: enhancement

#211 fix: add missing fields
  src/api/interfaces/vault-earning.interface.ts
Labels: bug

#212 fix: add vault + price snapshot support
  mocks.pkg/__cache__/methods.json
  mocks.pkg/generated/ethereum/api/loadPricesSnapshots.json
  mocks.pkg/generated/ethereum/api/loadVaultSnapshots.json
  mocks.pkg/src/config/base.config.ts
  src/api/enums/index.ts
  src/api/index.ts
  src/api/interfaces/index.ts
  src/api/interfaces/vault-earning.interface.ts
  src/api/types/index.ts
  src/api/types/price-snapshots.ts
Labels: enhancement
