Repository Badger-Finance/badger-sdk, pull requests merged in 2022-09, with the labels that each got.

#256 fix: support call overrides on read methods
  mocks.pkg/package.json
  mocks.pkg/yarn.lock
  src/vaults/vaults.service.ts
  yarn.lock
Labels: enhancement

#257 fix: update overrides inputs + update mocks
  mocks.pkg/__cache__/methods.json
  mocks.pkg/generated/ethereum/vaults/listHarvests.json
  src/vaults/vaults.service.ts
Labels: bug

#258 fix: add vault dto v3
  mocks.pkg/package.json
  src/api/index.ts
  src/api/interfaces/index.ts
  src/api/interfaces/vault-dto-v3.interface.ts
  src/api/interfaces/vault-yield-summary.interface.ts
  src/api/interfaces/yield-source.interface.ts
  src/api/interfaces/yield-summary.interface.ts
Labels: enhancement

#259 fix: update exports
  mocks.pkg/package.json
  src/api/interfaces/index.ts
Labels: bug

#260 fix: update interfaces to support multi versioned api
  src/api/index.ts
  src/api/interfaces/index.ts
  src/api/interfaces/vault-dto-v2.interface.ts
  src/api/interfaces/vault-dto-v3.interface.ts
  src/api/interfaces/vault-dto.interface.ts
  src/api/interfaces/vault-yield-projection-v2.interface.ts
  src/api/interfaces/vault-yield-projection-v3.interface.ts
  src/api/interfaces/vault-yield-projection.interface.ts
  src/api/interfaces/yield-source.interface.ts
  src/api/interfaces/yield-summary.interface.ts
Labels: enhancement

#261 feat: add txs string to vault performance events
  src/vaults/__snapshots__/vaults.utils.spec.ts.snap
  src/vaults/interfaces/vault-performance-event.ts
  src/vaults/vaults.utils.spec.ts
  src/vaults/vaults.utils.ts
Labels: enhancement

#262 fix: implement v3 vault queries
  mocks.pkg/__cache__/methods.json
  mocks.pkg/generated/ethereum/api/loadVaultV3.json
  mocks.pkg/generated/ethereum/api/loadVaultsV3.json
  mocks.pkg/src/config/base.config.ts
  src/api/index.ts
  src/vaults/vaults.utils.spec.ts
Labels: enhancement

#263 fix: update vaults harvests v3 response mocks
  mocks.pkg/__cache__/methods.json
  mocks.pkg/generated/ethereum/api/loadSchedule.json
  mocks.pkg/generated/ethereum/api/loadVault.json
  mocks.pkg/generated/ethereum/api/loadVaultHarvests.json
  mocks.pkg/generated/ethereum/api/loadVaultHarvestsV3.json
  mocks.pkg/generated/ethereum/api/loadVaults.json
  mocks.pkg/src/config/base.config.ts
  src/api/enums/index.ts
  src/api/enums/yield-type.enum.ts
  src/api/index.ts
  src/api/interfaces/index.ts
  src/api/interfaces/vault-earning.interface.ts
  src/api/interfaces/yield-event.interface.ts
Labels: enhancement

#264 refactor: utilize barrelsby for generation
  barrelsby.config.json
  package.json
  src/api/enums/index.ts
  src/api/interfaces/index.ts
  src/api/types/index.ts
  src/ibbtc/enums/index.ts
  src/ibbtc/interfaces/index.ts
  src/registry/enums/index.ts
  src/registry/interfaces/index.ts
  src/rewards/interfaces/index.ts
  src/tokens/interfaces/index.ts
  src/vaults/enums/index.ts
  src/vaults/interfaces/index.ts
  yarn.lock
Labels: enhancement

#265 fix: add created at block to query
  src/graphql/fragments/sett.fragment.graphql
  src/graphql/generated/badger.ts
Labels: enhancement

#268 fix: add missing yield type
  src/api/enums/yield-type.enum.ts
  src/api/interfaces/index.ts
  src/tokens/interfaces/index.ts
Labels: enhancement

#269 fix: add duration to yield event
  package.json
  src/api/interfaces/yield-event.interface.ts
  yarn.lock
Labels: enhancement

#270 fix: update graph mocks
  mocks.pkg/generated/ethereum/graph/loadSett.json
  mocks.pkg/generated/ethereum/graph/loadSetts.json
Labels: enhancement

#273 fix: allow registry acl lookups
  mocks.pkg/__cache__/methods.json
  mocks.pkg/generated/ethereum/api/loadPricesSnapshots.json
  mocks.pkg/generated/ethereum/api/loadVaultChart.json
  mocks.pkg/generated/ethereum/api/loadVaultSnapshots.json
  mocks.pkg/generated/ethereum/registry/getAuthorVaults.json
  mocks.pkg/generated/ethereum/registry/getDevelopmentVaults.json
  mocks.pkg/generated/ethereum/registry/getProductionVaults.json
  mocks.pkg/generated/ethereum/vaults/loadVault.json
  mocks.pkg/src/config/base.config.ts
  src/registry/registry.service.ts
  src/vaults/interfaces/load-vault-options.interface.ts
  src/vaults/vaults.service.ts
Labels: bug, enhancement

#274 fix: allow development vaults on load
  src/vaults/vaults.service.ts
Labels: enhancement

#275 fix: avoid overwriting production vaults with development definitions
  src/vaults/vaults.service.ts
Labels: bug

#276 fix: update harvests mocks
  mocks.pkg/__cache__/methods.json
  mocks.pkg/generated/ethereum/api/loadVaultHarvestsV3.json
  mocks.pkg/generated/ethereum/vaults/loadVault.json
Labels: enhancement
